services:
  - type: web
    name: aviator-bot
    env: python
    runtime: python-3.11
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
